
################################
#Project Euler

#Problem Statement 2
#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


################################
import time
import math

maxNumber=4000000


def two_sumFibNum():
		
	secondLast=1
	last=2
	sumFib=last
	for n in range(1,maxNumber):
		next=secondLast+last 
		secondLast=last
		last=next
		if (next % 2 == 0):		
		  sumFib=sumFib+next
		  #print(next)			
		if (sumFib>maxNumber):
			break
						
	print(sumFib)
	return sumFib

#time for execution of script
start_time = time.time()
two_sumFibNum()
print("--- %s seconds ---" % (time.time() - start_time))
